name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release src/Elmah.Io.NLog/Elmah.Io.Nlog.csproj /p:Version=5.1.${{ github.run_number }}-pre
    - name: Install dotnet-validate
      run: dotnet tool install --global dotnet-validate --version 0.0.1-preview.304
    - name: Validate
      run: dotnet-validate package local src/Elmah.Io.NLog/bin/Release/Elmah.Io.NLog.5.1.${{ github.run_number }}-pre.nupkg
    - name: Push
      run: dotnet nuget push src/Elmah.Io.NLog/bin/Release/Elmah.Io.NLog.5.1.${{ github.run_number }}-pre.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}
